spring.application.name=notification-service

## Kafka configuration
spring.kafka.bootstrap-servers=${KAFKA_BROKERS:localhost:9093}
kafka.ledger.topic=${KAFKA_LEDGER_TOPIC:transaction-created}
kafka.ledger.group-id=${KAFKA_LEDGER_GROUP_ID:notification-service-group}

## Docker-Compose configuration
spring.docker.compose.file=../compose.yaml
spring.docker.compose.start.command=up
spring.docker.compose.stop.command=stop
spring.docker.compose.stop.timeout=1m