<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.bantunes82</groupId>
    <artifactId>bank-services</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>ledger-service</module>
        <module>notification-service</module>
    </modules>
</project>