spring.application.name=ledger-service

## HTTP configuration
server.port=8081
server.servlet.context-path=/ledger-service
# Avoids Spring removing "X-Forwarded-For" headers
server.forward-headers-strategy=none

## Database configuration
database.dbname=${DS_DB_NAME:ledger_service_database}
database.hostname=${DS_HOST:127.0.0.1}
database.port=${DS_PORT:5432}
spring.datasource.url=jdbc:postgresql://${database.hostname}:${database.port}/${database.dbname}
spring.datasource.username=${DS_LOGIN:ledger}
spring.datasource.password=${DS_PASSWORD:secret}
spring.datasource.hikari.minimum-idle=${MIN_DB_POOL_SIZE:1}
spring.datasource.hikari.maximum-pool-size=${MAX_DB_POOL_SIZE:16}
# auto-commit forces spring to acquire a connection at the start of a transactional method
# and commit the transaction at each query
# this lost control waste resources and hold connection for longer then necessary
spring.datasource.hikari.auto-commit=false

## Hibernate configuration
#With this setup, Spring Boot application will first apply missing Flyway scripts to the database and then check if the
#JPA and database model match during startup.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# open-in-view holds the connection open during the whole http request execution
# even after the transaction is commited and finished, for no good reason
spring.jpa.open-in-view=false

## Logging configuration
logging.level.root=INFO
logging.group.application=com.bantunes82.ledger
logging.level.application=INFO

## API Versioning configuration
spring.mvc.apiversion.use.path-segment=1
spring.mvc.apiversion.supported=1.0,2.0
spring.mvc.apiversion.default=1.0

## Jackson configuration
spring.jackson.serialization.indent-output=true
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.deserialization.accept-empty-string-as-null-object=true

## Kafka configuration
kafka.brokers=${KAFKA_BROKERS:localhost:9092}
kafka.ledger.topic=${KAFKA_LEDGER_TOPIC:transaction-created}

## Debezium configuration
debezium.table.include.list=public.outbox

## Health configuration
management.endpoints.web.exposure.include=health,info,env,configprops
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.readiness.include=readinessState,db

## Docker-Compose configuration
spring.docker.compose.file=../compose.yaml
spring.docker.compose.start.command=up
spring.docker.compose.stop.command=stop
spring.docker.compose.stop.timeout=1m

## Application information
info.app.encoding=@project.build.sourceEncoding@
info.app.java.source=@language.compiler.level@
info.app.java.target=@language.compiler.level@


## Virtual Thread Configuration
spring.threads.virtual.enabled=true